apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - clusterroles.yaml
  - platform-admin.yaml
  - rolebindings.yaml
  - breakglass.yaml
  - argocd-rbac-configmap-patch.yaml
