apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crd-guardrailconfig.yaml
  - guardrailconfig-default.yaml
  - vap-critical-delete.yaml
  - vap-critical-delete-bindings.yaml
  - vap-deletion-tracker.yaml
  - vap-critical-label-control.yaml
  - vap-impersonation-dry-run-only.yaml
  - vap-gitops-only-mutation.yaml
  - vap-rbac-escalation-audit.yaml
  - reaper-cronjob.yaml
